### ISSUE TITLE
Webrtc connection lost, then crash because of webrtc API not found

### ISSUE THREAD

**Issue by whatisor** [whatisor/mediasoup-demo-android#2]
03-14 17:03:49.775 4104-4104/com.immertec.vr W/WebSocketTransport: onClose() code: 3, reason: WebSockets connection lost
03-14 17:03:49.775 4104-4104/com.immertec.vr W/Peer: onDisconnected()
03-14 17:03:49.785 4104-4304/com.immertec.vr I/org.webrtc.Logging: WebRtcAudioRecord: stopRecording
03-14 17:03:49.785 4104-4304/com.immertec.vr I/org.webrtc.Logging: WebRtcAudioRecord: stopThread
03-14 17:03:49.812 4104-4304/com.immertec.vr I/org.webrtc.Logging: WebRtcAudioEffects: release
03-14 17:03:49.812 4104-4304/com.immertec.vr I/org.webrtc.Logging: WebRtcAudioRecord: releaseAudioResources
03-14 17:03:49.826 4104-4304/com.immertec.vr I/org.webrtc.Logging: NetworkMonitor: Stop monitoring with native observer -1748804480
03-14 17:03:49.837 4104-4155/com.immertec.vr E/RoomClient: onTransportClose(), micProducer
03-14 17:03:49.839 4104-4304/com.immertec.vr I/org.webrtc.Logging: WebRtcAudioManager: dispose@[name=Thread-255, id=255]
03-14 17:03:49.845 4104-4303/com.immertec.vr W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[26,tid=4303,Native,Thread*=0x99656900,peer=0x12c850a0,"signaling_threa - 4303"]
03-14 17:03:49.846 4104-4322/com.immertec.vr E/art: No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)
03-14 17:03:49.847 4104-4322/com.immertec.vr E/AndroidRuntime: FATAL EXCEPTION: AudioTrackJavaThread
    Process: com.immertec.vr, PID: 4104
    java.lang.Error: FATAL EXCEPTION [AudioTrackJavaThread]
    Unity version     : 2018.4.18f1
    Device model      : unknown Android SDK built for x86
    Device fingerprint: Android/sdk_google_phone_x86/generic_x86:6.0/MASTER/5525988:userdebug/test-keys
    
    Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)
        at org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(Native Method)
        at org.webrtc.voiceengine.WebRtcAudioTrack.access$400(WebRtcAudioTrack.java:28)
        at org.webrtc.voiceengine.WebRtcAudioTrack$AudioTrackThread.run(WebRtcAudioTrack.java:147)

**Comment by whatisor** [comment]
WebRTCAudioTrack bug when audio consumer does NOT run on main thread.
